2019-05-14 20:25:14,792 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:25:15,133 - bfasbot - INFO - Checking Databased...
2019-05-14 20:25:15,133 - bfasbot - INFO - Check done.
2019-05-14 20:25:15,430 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:25:17,792 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:25:17,792 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:26:50,279 - bfasbot - ERROR - There was an exception in  error_handler
Traceback (most recent call last):
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1334, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 545676576687

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bfasbot/exception_decor.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/app/bfasbot/modules/whois.py", line 21, in error_handler
    raise e
  File "/app/bfasbot/modules/whois.py", line 77, in who_is
    get_user = BOT.get_chat(int(cmd)).id
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/methods/chats/get_chat.py", line 70, in get_chat
    peer = self.resolve_peer(chat_id)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1363, in resolve_peer
    id=[types.InputUser(user_id=peer_id, access_hash=0)]
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1051, in send
    r = self.session.send(data, retries, timeout)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 428, in send
    return self._send(data, timeout=timeout)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 394, in _send
    message = self.msg_factory(data)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/object.py", line 43, in __len__
    return len(self.write())
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/functions/users/get_users.py", line 60, in write
    b.write(Vector(self.id))
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in __new__
    for i in value
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    for i in value
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/types/input_user.py", line 58, in write
    b.write(Int(self.user_id))
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/int.py", line 32, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
OverflowError: int too big to convert
2019-05-14 20:26:50,287 - pyrogram.client.ext.dispatcher - ERROR - int too big to convert
Traceback (most recent call last):
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1334, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 545676576687

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/ext/dispatcher.py", line 157, in update_worker
    handler.callback(self.client, *args)
  File "/app/bfasbot/modules/whois.py", line 79, in who_is
    error_handler(bot, message, e)
  File "/app/bfasbot/modules/whois.py", line 77, in who_is
    get_user = BOT.get_chat(int(cmd)).id
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/methods/chats/get_chat.py", line 70, in get_chat
    peer = self.resolve_peer(chat_id)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1363, in resolve_peer
    id=[types.InputUser(user_id=peer_id, access_hash=0)]
  File "/app/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1051, in send
    r = self.session.send(data, retries, timeout)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 428, in send
    return self._send(data, timeout=timeout)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 394, in _send
    message = self.msg_factory(data)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/object.py", line 43, in __len__
    return len(self.write())
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/functions/users/get_users.py", line 60, in write
    b.write(Vector(self.id))
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in __new__
    for i in value
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    for i in value
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/types/input_user.py", line 58, in write
    b.write(Int(self.user_id))
  File "/app/.local/lib/python3.5/site-packages/pyrogram/api/core/primitives/int.py", line 32, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
OverflowError: int too big to convert
2019-05-14 20:29:36,719 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:29:37,033 - bfasbot - INFO - Checking Databased...
2019-05-14 20:29:37,033 - bfasbot - INFO - Check done.
2019-05-14 20:29:37,232 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:29:38,666 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:29:38,666 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:40:37,151 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:40:37,589 - bfasbot - INFO - Checking Databased...
2019-05-14 20:40:37,589 - bfasbot - INFO - Check done.
2019-05-14 20:40:37,812 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:40:44,911 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:40:44,912 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:41:14,515 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:41:14,831 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 108, in <module>
    LOGS.info("Checking Databased...")
NameError: name 'LOGS' is not defined
2019-05-14 20:41:18,609 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:41:18,761 - bfasbot - INFO - Checking Databased...
2019-05-14 20:41:18,766 - bfasbot - INFO - Check done.
2019-05-14 20:41:18,883 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:41:20,203 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:41:20,203 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:41:27,683 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:41:28,072 - bfasbot - INFO - Checking Databased...
2019-05-14 20:41:28,073 - bfasbot - INFO - Check done.
2019-05-14 20:41:28,231 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:41:29,748 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:41:29,748 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:41:34,108 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:41:34,721 - bfasbot - INFO - Checking Databased...
2019-05-14 20:41:34,722 - bfasbot - INFO - Check done.
2019-05-14 20:41:35,064 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:41:37,031 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:41:37,031 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:41:56,286 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:41:56,394 - bfasbot - INFO - Checking Databased...
2019-05-14 20:41:56,399 - bfasbot - INFO - Check done.
2019-05-14 20:41:56,544 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:41:58,657 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:41:58,657 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:42:08,629 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:08,877 - bfasbot - INFO - Checking Databased...
2019-05-14 20:42:08,878 - bfasbot - INFO - Check done.
2019-05-14 20:42:09,175 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:42:11,207 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:11,391 - bfasbot - INFO - Checking Databased...
2019-05-14 20:42:11,392 - bfasbot - INFO - Check done.
2019-05-14 20:42:11,509 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:42:13,059 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:42:13,059 - bfasbot - INFO - Your bot is Version 0.4.5

2019-05-14 20:42:42,045 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:42,359 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 51, in <module>
    LOGS = setup_logging("logging.txt")
  File "/app/bfasbot/__init__.py", line 50, in setup_logging
    return logger
NameError: name 'logger' is not defined
2019-05-14 20:42:44,569 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:45,153 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 110, in <module>
    LOGS.info("Checking Databased...")
NameError: name 'LOGS' is not defined
2019-05-14 20:42:47,436 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:47,535 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 110, in <module>
    LOGS.info("Checking Databased...")
NameError: name 'LOGS' is not defined
2019-05-14 20:42:50,416 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:50,552 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 31, in <module>
    LOGS
NameError: name 'LOGS' is not defined
2019-05-14 20:42:53,162 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:53,377 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/bfasbot/__init__.py", line 31, in <module>
    LOGS = logger = logging.getLogger(__name__)
NameError: name 'LOGS' is not defined
2019-05-14 20:42:54,476 - pyrogram.crypto.aes - INFO - Using TgCrypto
2019-05-14 20:42:54,587 - bfasbot - INFO - Checking Databased...
2019-05-14 20:42:54,588 - bfasbot - INFO - Check done.
2019-05-14 20:42:54,668 - bfasbot - INFO - Modules to load:
1start, admin, beta, blacklist, dogbin, evaluation, getinfo, gog_wiki, greet, loads, markdown, menprivate, mirrorace, misc, poll, purge, reboot, repo, torrents, transfer, update, whois

2019-05-14 20:42:56,282 - bfasbot - INFO - Your bot is running! Test it by typing .up in any chat.
2019-05-14 20:42:56,282 - bfasbot - INFO - Your bot is Version 0.4.5

